from .crs_baseline import CRS_BASELINE
import torch

def load_crs_baseline(
    lm_type="meta-llama/Llama-3.2-1B-Instruct",
    retrieval_type="bm25",
    item_db_name: str = "talkpl-ai/TalkPlayData-Challenge-Track-Metadata",
    user_db_name: str = "talkpl-ai/TalkPlayData-Challenge-User-Metadata",
    track_split_types: list[str] = ["all_tracks"],
    user_split_types: list[str] = ["all_users"],
    corpus_types: list[str] = ["track_name", "artist_name", "album_name"],
    cache_dir="./cache",
    device="cuda",
    attn_implementation="eager",
    dtype=torch.bfloat16,
    use_gemini_expansion=False,
    gemini_model_name="gemini-3.1-flash-lite",
    gemini_cache_dir="./cache/gemini_expansions",
    gemini_expansion_mode="tag_query",
    gemini_topk_per_reference=50,
    gemini_rrf_k=60,
    include_original_query_in_fusion=False,
    original_query_weight=2.0,
    gemini_reference_weight=1.0,
    gemini_max_reference_tracks=None,
    gemini_fusion_method="rrf",
    rerank_tag_weight=0.04,
    rerank_artist_profile_weight=0.04,
    rerank_decade_weight=0.02,
    hybrid_bm25_corpus_types=None,
    hybrid_bm25_topk_per_reference=100,
    hybrid_bm25_weight=0.12,
    hybrid_artist_match_weight=0.03,
    hybrid_album_match_weight=0.02,
    hybrid_multi_source_weight=0.03,
    retrieval_only=False,
):
    return CRS_BASELINE(
        lm_type=lm_type,
        retrieval_type=retrieval_type,
        item_db_name=item_db_name,
        user_db_name=user_db_name,
        track_split_types=track_split_types,
        user_split_types=user_split_types,
        corpus_types=corpus_types,
        cache_dir=cache_dir,
        device=device,
        attn_implementation=attn_implementation,
        dtype=dtype,
        use_gemini_expansion=use_gemini_expansion,
        gemini_model_name=gemini_model_name,
        gemini_cache_dir=gemini_cache_dir,
        gemini_expansion_mode=gemini_expansion_mode,
        gemini_topk_per_reference=gemini_topk_per_reference,
        gemini_rrf_k=gemini_rrf_k,
        include_original_query_in_fusion=include_original_query_in_fusion,
        original_query_weight=original_query_weight,
        gemini_reference_weight=gemini_reference_weight,
        gemini_max_reference_tracks=gemini_max_reference_tracks,
        gemini_fusion_method=gemini_fusion_method,
        rerank_tag_weight=rerank_tag_weight,
        rerank_artist_profile_weight=rerank_artist_profile_weight,
        rerank_decade_weight=rerank_decade_weight,
        hybrid_bm25_corpus_types=hybrid_bm25_corpus_types,
        hybrid_bm25_topk_per_reference=hybrid_bm25_topk_per_reference,
        hybrid_bm25_weight=hybrid_bm25_weight,
        hybrid_artist_match_weight=hybrid_artist_match_weight,
        hybrid_album_match_weight=hybrid_album_match_weight,
        hybrid_multi_source_weight=hybrid_multi_source_weight,
        retrieval_only=retrieval_only,
    )
